Roulette_spin_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  roulette_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: table_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
