# How to publish from cmd line: rosservice call darknet_multiplexer/configure_active_cameras "{actives:[1,0,1,0,1,0]}"
# DOWNCAM_INDEX=5
# TORPEDO_INDEX=6
# NUMBER_CAMERAS=7
bool[] actives
---
bool success