perception_control:
  bb_controllers:

    # Success Thresholds
    succeeded_x_pixel_dist: 10
    succeeded_y_pixel_dist: 10

    # Controllers
    proportional:
      downcam:
        drive:
          max_setpoint: 1.0
          maxout_pixel_dist: 100
        strafe:
          max_setpoint: 1.0
          maxout_pixel_dist: 100
      occam:
        drive:
          max_setpoint: 0.5 # Reality 1.0
          maxout_pixel_dist: 50 # 100
        strafe:
          max_setpoint: 1.0
          maxout_pixel_dist: 50
        yaw:
          max_setpoint: 0.3
          maxout_pixel_dist: 100
        depth:
          max_setpoint: 0.2
          maxout_pixel_dist: 70
    
    rotational:
      timeout_frames: 50
      occam:
        rotation:
          carrot: 0.3
          threshold: 0.1
        frames_ns: "leviathan/description/"
        frames: ["occam1_frame_optical", "occam2_frame_optical", "occam3_frame_optical", "occam4_frame_optical"]
        frame_offset: 1.25664 # radians


  path_orient:
    yaw_setpoint_carrot: 0.5
    bang_bang_deadzone: 10.0    # Absolute value of hough lines slope before entering deadzone
