perception_control:
  bb_controllers:
    proportional:
      downcam:
        drive:
          max_setpoint: 1.0
          maxout_pixel_dist: 200
        strafe:
          max_setpoint: 1.0
          maxout_pixel_dist: 200