StartGate_1:
- -6.75
- 3.73
- -0.5
- -2.09
buoy_jiangshi_1:
- 0.73
- -1.22
- -0.9
- -1.83
dropper_garlic_1:
- -3.63
- -3.02
- -3.5
- 0.0
leviathan/description:
- 7.98
- -0.5
- 0.0
- 3.14
mappings:
  droppers:
    model: dropper_garlic_1
    prior_z: -1.0
  jiangshi:
    model: buoy_jiangshi_1
    prior_z: -1.5
  start_gate:
    model: StartGate_1
    prior_z: -2.0
  torpedos:
    model: vampire_stake_1
    prior_z: -2.0
vampire_stake_1:
- -7.72
- -3.95
- -2.4
- 1.57
