# Default fake yolo launch for leviathan
# generates bounding boxes similar to yolo for testing without GPU grunt, or before network is trained
yolo_faker:
 bounding_boxes_topic: 'cusub_perception/darknet_ros/bounding_boxes'
 sub_pose_topic: 'description/pose_gt'

# Cameras to run fake yolo on
 cameras:
   occam0:
     frame: 'leviathan_gt/occam0_frame'
     image_topic: 'cusub_common/occam/image0'
     debug_image_enabled: True
     debug_image_topic: 'cusub_common/occam/image0_debug'
     camera_info_topic: 'cusub_common/occam/image0/camera_info'
   downcam:
     frame: 'leviathan_gt/downcam_frame'
     image_topic: 'cusub_common/downcam'
     debug_image_enabled: True
     debug_image_topic: 'cusub_common/downcam_debug'
     camera_info_topic: 'cusub_common/downcam/camera_info'

# Objects to run fake yolo on
# You can have multiple classes per object with different point offsets, like the 2 start gate poles
 objects:
  jiangshi:
   link: 'buoy_jiangshi_1/base_link'
   odom_topic: '/buoy_jiangshi_1/pose_gt'
   classes:
    - name: 'vampire_cute'
      debug_color: [0, 255, 0]
      points: [ [-0.4048, -0.0508, 0.6096], [ 0.4048, -0.0508,  0.6096], [ -.4048,  0.0508,  0.6096], [ 0.4048,  0.0508,  0.6096], [-0.4048, -0.0508, -.6096], [ 0.4048, -0.0508,  -.6096], [ -.4048,  0.0508,  -.6096], [ 0.4048,  0.0508,  -.6096] ]
  path0:
   link: 'PathMarker_1/base_link'
   odom_topic: '/PathMarker_1/pose_gt'
   classes:
    - name: 'path'
      debug_color: [0, 255, 0]
      points: [ [0.01, 0.01, 0.01], [-0.01, 0.01, 0.01], [-0.01, -0.01, 0.01], [-0.01, 0.01, -0.01], [0.01, -0.01, 0.01], [0.01, -0.01, -0.01], [0.01, 0.01, -0.01], [-0.01, -0.01, -0.01] ]
  # startgate:
  #  link: 'StartGate_1/base_link'
  #  odom_topic: '/StartGate_1/pose_gt'
  #  classes:
  #   - name: 'start_gate_pole'
  #     debug_color: [0, 255, 0]
  #     points: [[ 1.450, -0.075,  0.000],[ 1.650, -0.075,  0.000],[ 1.450,  0.075,  0.000],[ 1.650,  0.075,  0.000],[ 1.450, -0.075, -1.500],[ 1.650, -0.075, -1.500],[ 1.450,  0.075, -1.500],[ 1.650,  0.075, -1.500]]
  #   - name: 'start_gate_pole'
  #     debug_color: [0, 255, 0]
  #     points: [[-1.450, -0.075,  0.000],[-1.650, -0.075,  0.000],[-1.450,  0.075,  0.000],[-1.650,  0.075,  0.000],[-1.450, -0.075, -1.500],[-1.650, -0.075, -1.500],[-1.450,  0.075, -1.500],[-1.650,  0.075, -1.500]]