GoldChip_1:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  button_effort_controller:
    type: effort_controllers/JointEffortController
    joint: goldchip_button_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
