map_dims:
  fig_qt_offset:
  - 54
  - 54
  image_horizontal_axis_right: +y
  image_vertical_axis_down: +x
  world_coords_of_top_left_corner_of_image:
  - -9
  - -6
  x_len: 12
  x_pixels: 480
  y_len: 18
  y_pixels: 720
priors:
  droppers:
    prior_depth: -1.0
    qtlocation:
    - 168
    - 173
    - 0
    sim_model: dropper_garlic_1
  jiangshi:
    prior_depth: -1.5
    qtlocation:
    - 326
    - 54
    - 105
    sim_model: buoy_jiangshi_1
  leviathan:
    qtlocation:
    - 166
    - 625
    - 0
    sim_model: leviathan/description
  start_gate:
    prior_depth: -2.0
    qtlocation:
    - 145
    - -1
    - 120
    sim_model: StartGate_1
  torpedos:
    prior_depth: -2.0
    qtlocation:
    - 28
    - -3
    - 90
    sim_model: vampire_stake_1
sim_truth_depths:
  StartGate_1: -0.5
  buoy_jiangshi_1: -0.9
  dropper_garlic_1: -3.5
  leviathan/description: 0.0
  vampire_stake_1: -2.4
