localizer:
  classes:
    start_gate_pole : hough # hough, ...
    vampire_cute : jiangshi_watershed
    fat_head : ignore
    slick : ignore
    no_torso : ignore
    walking : ignore
    dice5 : ignore
  hough:
    three_legs : False  # true, false

