localizer:
  classes:
    start_gate_pole : hough # hough, ...
    vampire_cute : jiangshi_watershed
    vampire_walking : ignore
    vampire_fathead : ignore
    vampire_flying : ignore
  hough:
    three_legs : False  # true, false

