localizer:
  classes:
    start_gate_pole : ignore # hough, ...
    vampire_cute : zp
    path: zp
    vampire_fathead: ignore
    vampire_flying: ignore
    vampire_no_torso: ignore
    bat: zp
    wolf: zp
    dropper_cover: zp
    pinger: ignore
    coffin: zp
    dracula: ignore
    heart: ignore
    open_oval: ignore
    lever: ignore
  zp:
    height:
      bat: -4.3
      wolf: -4.3
      dropper_cover: -4.2
      coffin: -3.3
      path: -4.4
      vampire_cute: -3.3
  hough:
    three_legs : True  # true, false
  jiangshi_watershed:
    use_aspect_ratio : true
    aspect_ratio_90_deg: 0.1  # 0 degrees is 0.5

