localizer:
  classes:
    start_gate_pole : hough # hough, ...
    vampire_cute : jiangshi_watershed
    path: ignore
    vampire_fathead: ignore
    vampire_flying: ignore
    vampire_no_torso: ignore
    bat: ignore
    wolf: ignore
    dropper_cover: ignore
    pinger: ignore
    coffin: ignore
    dracula: ignore
    heart: ignore
    open_oval: ignore
    lever: ignore
  hough:
    three_legs : True  # true, false
  jiangshi_watershed:
    use_aspect_ratio : true
    aspect_ratio_90_deg: 0.1  # 0 degrees is 0.5

