# Mission Config of the sub
# ALL UNITS IN M

using_sim_params : False
manager_task_status_pub_rate: 1

startup_delay: 0

tasks:
 startup:
  manager_info:
    timeout_secs: 10 # wait time at surface
  depth: -0.5
  dive_time: 3
  
 start_gate:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'uh_oh'
  # prior: [0,-8.0,-1.5]
  # prior: [-9.5,-9.7,-0.75] D
  prior: [11.5,9,-0.75] # A, using the odom from day 2
  # prior: [13.27, 1.3, -0.5] # A, using the axes of transdec 
  # prior: [-9, 2, -0.5] # B    KEEP IN MIND IF TOP IS ON SURFACE
  # prior: [12.5, -7.7, -0.75] # C
  prior: [-14, 7, -0.75] # C
  dist_behind_gate: 1.0
  third_leg_adjustment: 0.5
  replan_thresh: 1.0
  style_dist: 2.0
  do_style: True
  spin_carrot_rads: 0.7

 jiangshi:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip'
    outcome_timed_out: 'skip'
  # prior: [-17, -19,-1.8] # D?
  # prior: [-18, 6, -1.8] # C
  # prior: [18, -14, -1.8] # B?
#   prior: [16, 15, -1.8] # A
  method: vs        # solvepnp OR vs
  solvepnp:
    use_buoys_yaw: False   # If false, the sub will assume the buoy is facing twd sub
    replan_thresh: 1.0
    slay_dist: 0.0
    approach_dist: 2.0
  visual_servo: # approach and slay
    goal_percentage_of_frame: 0.4    # Percentage of image for target class
    slay_timeout: 10                 # How long the slay will last
    slay_carrot: 0.7                 # controls the speed when slaying the buoy by adjusting drive setpoint
    target_pixel_threshold: 50    # how close to our target do we need to be    

 triangle:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  # prior: [-19.5, 4.5, -2] # C
  prior: [17, 12, -1.8] # A
  do_orbit: false
  orbit_right: true
  strafe_carrot: 0.2
  single_class_time: 1
  target_vampire: 'vampire_flying'
  visual_servo: # approach and slay
    goal_percentage_of_frame: 0.4    # Percentage of image for target class
    slay_timeout: 10                 # How long the slay will last
    slay_carrot: 0.7                 # controls the speed when slaying the buoy by adjusting drive setpoint
    target_pixel_threshold: 50    # how close to our target do we need to be
  mikes_method:
    do: false
    go_over_jiangshi_depth: -0.7
    meters_fwd: 2.0

 dropper:
  manager_info:
    timeout_secs: 180
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  # prior: [-2.5,2.0, 0.0] # Won't matter much b/c we'll almost immediately see it after the SG
  # prior: [-29,12, 0.0]
#  prior: [19, 17, -1.25] # A
  prior: [-26, 15, -1.25]
  target_pixel_threshold: 40   # Goal box size around our target pixel for visual servoing, if inside the box we will be successful
  drop_timeout: 60
  drop_depth: -2.25
  approach_depth: -1.25
  drive_carrot: 1.0
  depth_carrot: 0.5
  drop_depth_timeout: 60

 octagon:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  #prior: [-19.5, 4.5, -2] # C
  # prior: [19.5, -9, -2] # B?
#  prior: [30.7, 23.4, -1] # A
  prior: [-27, 22, -1] # C

  target_pixel_threshold: 30   # Goal box size around our target pixel for visual servoing, if inside the box we will be successful
  approach_depth: -1
  depth_carrot: 0.2
  drive_carrot: 1.0
  octagon_height: 0.0
  finish_depth: -1.5
  finish_depth_thresh: 0.4

 debug:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  target_pixel_threshold: 40   # Goal box size around our target pixel for visual servoing, if inside the box we will be successful
  drop_timeout: 30
  drop_depth: -0.4
  drop_depth_thresh: 0.1
  approach_depth: -0.15
  drive_carrot: 1.0 # note 0.5 doesn't move the sub forward
  depth_carrot: 0.1

mission_tasks: # Tasks To Do In Order
 - startup
 - start_gate
 - octagon
 - dropper
 - triangle
 - jiangshi