# Mission Config of the sub
# ALL UNITS IN M

using_sim_params : False
manager_task_status_pub_rate: 1

startup_delay: 0

tasks:
 startup:
  manager_info:
    timeout_secs: 10 # wait time at surface
  depth: -0.5
  dive_time: 3
  
 start_gate:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'uh_oh'
  # prior: [0,-8.0,-1.5]
  prior: [-9.5,-9.7,-0.75]
  # prior: [11.5,9,-0.75]  A
  # prior: [-10,3,-0.75]
  dist_behind_gate: 1.0
  third_leg_adjustment: 0.75
  replan_thresh: 1.0
  style_dist: 2.0
  do_style: True
  spin_carrot_rads: 0.7

 jiangshi:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip'
    outcome_timed_out: 'skip'
  prior: [-17, -19,-1.8]
  method: vs        # solvepnp OR vs
  solvepnp:
    use_buoys_yaw: False   # If false, the sub will assume the buoy is facing twd sub
    replan_thresh: 1.0
    slay_dist: 0.0
    approach_dist: 2.0
  visual_servo: # approach and slay
    goal_percentage_of_frame: 0.4    # Percentage of image for target class
    slay_timeout: 10                 # How long the slay will last
    slay_carrot: 0.7                 # controls the speed when slaying the buoy by adjusting drive setpoint
    target_pixel_threshold: 50    # how close to our target do we need to be    

 dropper:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  prior: [-2.5,2.0, 0.0] # Won't matter much b/c we'll almost immediately see it after the SG
  centering_time: 5            # Time between first centered feedback & when we check if we're centered again
  target_pixel_threshold: 40   # Goal box size around our target pixel for visual servoing, if inside the box we will be successful
  drop_timeout: 30
  search_depth: -0.01
  drop_depth: -3.8
  drop_thresh: 0.5

mission_tasks: # Tasks To Do In Order
 - startup
 - start_gate
