# Mission Config of the sub
# ALL UNITS IN M

# Search Algorithms: simple

tasks:
 naive_visual_servo_objective:
  prior: [0,0,0]
  search_alg: simple

  failed_repeat: false
  object_localizers:
    dice1: dice_box
    dice2: dice_box
    dice5: dice_box
    dice6: dice_box

mission_tasks: # Tasks To Do In Order
 - naive_visual_servo_objective
