# Mission Config of the sub
# ALL UNITS IN M

# Search Algorithms: simple

tasks:
 start_gate:
  prior: [8,-1,-1.5]
  search_alg: simple
  dist_behind_gate: 1.0
  failed_repeat: true
  object_localizers:
    start_gate_pole: ['gate_pnp_color', 'gate_midpoint']
 dice:
  prior: [1,1,-2.3]
  search_alg: simple
  failed_repeat: false
  targets: ['dice5', 'dice6']
  replan_threshold: 1.0
  approach_radius: 1.0
  orbital_radius: 2.0
  lockon_time: 5.0
  carrot_dist: 2.0
  backup_dist: 2.0
  x_accel_spike_thresh: -0.15
  object_localizers:
    dice1: dice_box
    dice2: dice_box
    dice5: dice_box
    dice6: dice_box
mission_tasks: # Tasks To Do In Order
 - dice
