# Mission Config of the sub
# ALL UNITS IN M

using_sim_params : False
manager_task_status_pub_rate: 1

startup_delay = 5

tasks:
 start_gate:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'uh_oh'
  # prior: [0,-8.0,-1.5]
  # prior: [11.5,7.5,-0.75]   A
  prior: [-10,3,-0.75]
  dist_behind_gate: 1.0
  third_leg_adjustment: 0.5
  replan_thresh: 1.0
  style_dist: 1.5
  do_style: True
  spin_carrot_rads: 0.7

 jiangshi:
  manager_info:
   timeout_secs: 0
   outcome_not_found: 'skip'
   outcome_timed_out: 'skip'
  prior: [-4,-1.0,-0.75]
  approach_dist: 2.0
  slay_dist: 3.0
  replan_thresh: 1.0
  imu_axis: 'y'
  jump_thresh: 1.0
  slay_timeout: 0
  use_buoys_yaw: False   # If false, the sub will assume the buoy is facing twd sub

 dropper:
  manager_info:
    timeout_secs: 0
    outcome_not_found: 'skip' # skip, later
    outcome_timed_out: 'skip'
  prior: [-2.5,2.0, 0.0] # Won't matter much b/c we'll almost immediately see it after the SG
  centering_time: 5            # Time between first centered feedback & when we check if we're centered again
  target_pixel_threshold: 40   # Goal box size around our target pixel for visual servoing, if inside the box we will be successful

  search_depth: -0.01
  drop_depth: -0.01
  drop_thresh: 0.5;

mission_tasks: # Tasks To Do In Order
 - dropper
